# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

# TODO make Container Registry more standardized and
#      provide instructions to create the connection
steps:
- task: Docker@2
  inputs:
    containerRegistry: 'dockerhub-mtyler'
    repository: 'contrast-java-agent'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    tags: |
      $(Build.BuildId)
      latest
